# ===============================
# DATABASE CONNECTION
# ===============================

spring.datasource.url = jdbc:mysql://switchyard.proxy.rlwy.net:14322/railway
spring.datasource.username = root
spring.datasource.password = LyCPQTkihOyBBOEHlYjhNgbuHYTyRLvo
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

# Am scos liniile cu MySQL8Dialect pentru c? nu mai exist? în Hibernate 7
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

# Op?ional, dac? tot vrei s? specifici platforma, folose?te varianta simpl?:
spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect